# Generated by Django 4.0.4 on 2022-06-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBooks',
        ),
    ]
