# Generated by Django 4.0.4 on 2022-06-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_books_available_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='mode',
            field=models.CharField(default='Dark Mode', max_length=20),
        ),
    ]
