# Generated by Django 4.0.4 on 2022-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarianRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarian_name', models.CharField(max_length=20)),
                ('librarian_password', models.CharField(max_length=20)),
                ('librarian_email', models.CharField(max_length=40)),
                ('librarian_shift', models.CharField(choices=[(0, 'Select your shift'), ('morning', '6am to 2pm'), ('afternoon', '2pm to 11pm')], default=0, max_length=30)),
                ('librarian_registration_date', models.CharField(max_length=30)),
                ('librarian_login_count', models.IntegerField(default=5)),
            ],
        ),
    ]
