# Generated by Django 4.0.4 on 2022-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_librarianregistration_librarian_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianregistration',
            name='librarian_security_code',
            field=models.IntegerField(default=0),
        ),
    ]
