# Generated by Django 4.0.4 on 2022-06-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=20)),
                ('student_password', models.CharField(max_length=20)),
                ('student_category', models.CharField(choices=[(0, 'Select Category'), ('bachelor-of-arts', 'Bachelor of Arts'), ('bba/bms', 'BMS/BBA'), ('btech-bachlor-of-engg./tech', 'Bachelor of Engg./Tech'), ('bachelor-of-commerce', 'Bachelor of Commerce'), ('bachelor-of-law', 'Bachelor of Law'), ('mbbs-bachelor-of-medicine', 'Bachelor of Medicine'), ('bachelor-of-science', 'Bachelor of Science'), ('intermediate', 'Intermediate'), ('ssc-10th-standard', '10th Standard')], default=0, max_length=30)),
                ('student_books_count', models.IntegerField(default=3)),
                ('student_login_count', models.IntegerField(default=5)),
                ('student_registration_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('librarian_email', models.CharField(max_length=50)),
                ('requested_date', models.DateField()),
                ('approved_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('return_approved_date', models.DateField()),
            ],
        ),
    ]
