# Generated by Django 4.0.4 on 2022-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_registration_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='fine_amount',
            field=models.IntegerField(default=0),
        ),
    ]
