# Generated by Django 4.0.4 on 2022-06-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
    ]
